#!/usr/bin/env python3
"""backup-restore-order -- computes the correct, foreign-key-dependency-safe
table order for restoring backups/<ts>/08_data.sql, replacing the old
alphabetical table order that caused FK-constraint violations on restore
(the "Known gap" previously documented in BACKUP_RUNBOOK.md).

Not part of the application runtime -- a backup-operator utility only.
No credentials embedded; operates on a static, explicit FK-edge list that
must be refreshed if the schema changes (see "How do I refresh the edge
list?" below).

--------------------------------------------------------------------------
THE BUG THIS REPLACES
--------------------------------------------------------------------------
08_data.sql was generated by iterating `pg_class` tables in
`order by c.relname` (plain alphabetical order) -- see BACKUP_RUNBOOK.md
step 11's DO block. Alphabetical order has no relationship to foreign-key
dependency order, so a restore could (and for this schema, provably does
-- e.g. 'age_groups' comes before 'clubs' alphabetically, but
age_groups.club_id REFERENCES clubs) hit FK-constraint violations when a
child table's INSERTs run before its parent table's INSERTs exist.

THE FIX
--------------------------------------------------------------------------
1. Build a directed graph: table -> {tables it has a NOT NULL FK to}.
   Only NOT NULL FK edges are treated as *hard* ordering constraints,
   because a hard (non-deferrable, NOT NULL) FK column has no legal
   restore order other than "parent row must exist before the INSERT
   that references it" -- there is no way to defer populating it.
2. Kahn's algorithm topologically sorts on that hard-edge graph. If a
   cycle is found among hard edges, this script FAILS LOUDLY (exit 1)
   instead of guessing -- that would be a genuine unsolvable ordering
   problem requiring a schema fix (e.g. making an FK deferrable or
   nullable), not something a restore-order script can paper over.
3. NULLABLE FK edges (e.g. bookings.invoice_id -> invoices,
   invoices does NOT reference bookings back, so this isn't even a
   cycle in this schema -- but shop_sales.invoice_id and
   club_membership_subscriptions.invoice_id are the same nullable
   pattern) are recorded separately as "soft" edges. They do NOT
   constrain insert order (the column can legally be NULL at insert
   time) but backfilling them correctly on restore requires a second
   pass: insert every row with the nullable FK column NULL, then run a
   deferred UPDATE once both sides of the relationship exist. This
   script emits that deferred-update table list explicitly so the
   restore procedure knows which columns need the two-phase treatment.
4. Self-referencing FKs (a table referencing its own primary key,
   e.g. customers.merged_into_customer_id) never constrain *between*
   table order -- they are same-table and always nullable in this
   schema -- but are called out separately since a naive per-row
   INSERT could still fail if row B (inserted after row A) is
   referenced by row A's self-FK. The generation script must emit
   self-referencing columns as NULL-at-insert too, backfilled in the
   same deferred-update pass.

Usage:
    python3 topo_sort_tables.py                  # print the order
    python3 topo_sort_tables.py --verify          # exit 0 if a valid
                                                    # topological order
                                                    # exists (dry-run
                                                    # check, no output)
    python3 topo_sort_tables.py --json            # machine-readable
                                                    # output for other
                                                    # tooling

How do I refresh the edge list if the schema changes?
--------------------------------------------------------------------------
Re-run this query against the live project (read-only, safe) via the
Supabase MCP execute_sql tool or `supabase db` and replace HARD_EDGES /
SOFT_EDGES / SELF_REF_COLUMNS below:

    select
      tc.table_name as child_table,
      kcu.column_name as fk_column,
      ccu.table_name as parent_table,
      a.attnotnull as fk_col_not_null
    from information_schema.table_constraints tc
    join information_schema.key_column_usage kcu
      on kcu.constraint_name = tc.constraint_name
     and kcu.constraint_schema = tc.constraint_schema
    join information_schema.constraint_column_usage ccu
      on ccu.constraint_name = tc.constraint_name
     and ccu.constraint_schema = tc.constraint_schema
    join pg_class c on c.relname = tc.table_name
                    and c.relnamespace = 'public'::regnamespace
    join pg_attribute a on a.attrelid = c.oid
                        and a.attname = kcu.column_name
                        and a.attnum > 0
    where tc.constraint_type = 'FOREIGN KEY'
      and tc.table_schema = 'public'
    order by tc.table_name, kcu.column_name;

Edge list last refreshed: 2026-09-03 (post-P2-remediation correction),
live against project gxkrtlvpjwxhcqdisyob (Postgres 17.6), 114
public-schema tables. Independent P2 verification of the M-14 fix found
the prior refresh (also stamped 2026-09-03, 112 tables) was already
stale by the time it was finalized: attendance_history and
gateway_webhook_rate_limit_state were added to the live schema by
same-day migrations (attendance_history_audit_trail_m8,
gateway_webhook_rate_limit_m5) roughly 3 hours before that refresh was
recorded. Both tables have hard (NOT NULL) FK edges only -- no deferred
UPDATE pass is needed for either. This refresh also no longer matches
backups/20260831T163434Z/09_manifest.json's table count, since that
snapshot predates both new tables; a fresh backup taken after this
correction will include them.
"""
import json
import sys

# All 114 public-schema tables as of the last refresh above (includes
# tables with zero FK edges -- they still need a position in the order,
# and Kahn's algorithm below naturally places zero-in-degree tables
# first regardless of whether they have any FK at all).
ALL_TABLES = [
    "age_groups", "attendance", "attendance_history", "audit_logs",
    "automatic_trial_entitlements",
    "booking_series", "bookings", "branches", "cash_shifts",
    "club_booking_policy", "club_gateway_connections",
    "club_gateway_provider_policy", "club_membership_freezes",
    "club_membership_number_sequences", "club_membership_plan_branches",
    "club_membership_plans", "club_membership_sale_keys",
    "club_membership_subscriptions", "club_memberships", "club_modules",
    "club_role_permissions", "club_roles", "clubs", "commercial_entitlements",
    "commercial_upgrade_requests", "contact_requests",
    "customer_photo_update_requests", "customers", "employee_cash_liabilities",
    "employee_cash_liability_ledger", "employee_cash_liability_settlement_keys",
    "enrollments", "expense_categories", "expenses", "field_blocks",
    "field_operating_hours", "fields", "gateway_webhook_rate_limit_state",
    "government_collection_policies",
    "group_schedule_slots", "groups", "guardian_links", "invoice_items",
    "invoice_number_sequences", "invoice_verification_tokens", "invoices",
    "manual_payment_claims", "membership_branches", "messaging_safety_settings",
    "notification_category_settings", "notification_consent",
    "notification_events", "notification_queue", "notification_suppressions",
    "official_collection_receipts", "payment_allocations",
    "payment_gateway_configs", "payment_gateway_providers",
    "payment_gateway_transactions", "payment_gateway_webhook_events",
    "payment_method_configs", "payment_proofs", "payment_reconciliations",
    "payments", "permission_dependencies", "permissions",
    "platform_custom_role_permissions", "platform_custom_roles",
    "platform_invoices", "platform_owner_pinned_clubs",
    "platform_owner_recent_clubs", "platform_payments", "platform_permissions",
    "platform_plans", "platform_role_permissions", "platform_roles",
    "platform_settings", "platform_staff_memberships", "platform_subscriptions",
    "platform_support_sessions", "players", "portal_invites", "pricing_rules",
    "profiles", "programs", "qr_credentials", "qr_scan_events", "refunds",
    "role_permissions", "roles", "seasons", "shop_categories",
    "shop_held_sale_items", "shop_held_sales", "shop_inventory_balances",
    "shop_inventory_locations", "shop_inventory_movements",
    "shop_product_variants", "shop_products", "shop_sale_items",
    "shop_sale_return_items", "shop_sale_returns", "shop_sales",
    "shop_stock_count_items", "shop_stock_counts", "shop_suppliers",
    "subscription_freezes", "subscriptions", "training_sessions",
    "whatsapp_accounts", "whatsapp_connection_events",
    "whatsapp_delivery_traces", "whatsapp_incidents",
    "whatsapp_root_cause_codes",
]

# (child_table, fk_column, parent_table) -- hard constraint: parent MUST
# be inserted before child. Self-referencing edges (child == parent) are
# intentionally excluded here (they never affect *between-table* order)
# and listed separately in SELF_REF_COLUMNS below.
HARD_EDGES = [
    ("age_groups", "club_id", "clubs"),
    ("attendance", "club_id", "clubs"),
    ("attendance", "player_id", "players"),
    ("attendance", "session_id", "training_sessions"),
    ("attendance_history", "attendance_id", "attendance"),
    ("attendance_history", "club_id", "clubs"),
    ("attendance_history", "player_id", "players"),
    ("attendance_history", "session_id", "training_sessions"),
    ("automatic_trial_entitlements", "club_id", "clubs"),
    ("booking_series", "club_id", "clubs"),
    ("booking_series", "customer_id", "customers"),
    ("booking_series", "field_id", "fields"),
    ("bookings", "branch_id", "branches"),
    ("bookings", "club_id", "clubs"),
    ("bookings", "customer_id", "customers"),
    ("bookings", "field_id", "fields"),
    ("branches", "club_id", "clubs"),
    ("cash_shifts", "branch_id", "branches"),
    ("cash_shifts", "club_id", "clubs"),
    ("club_booking_policy", "club_id", "clubs"),
    ("club_gateway_connections", "club_id", "clubs"),
    ("club_gateway_connections", "provider_key", "payment_gateway_providers"),
    ("club_gateway_provider_policy", "club_id", "clubs"),
    ("club_gateway_provider_policy", "provider_key", "payment_gateway_providers"),
    ("club_membership_freezes", "club_id", "clubs"),
    ("club_membership_freezes", "membership_subscription_id", "club_membership_subscriptions"),
    ("club_membership_number_sequences", "club_id", "clubs"),
    ("club_membership_plan_branches", "branch_id", "branches"),
    ("club_membership_plan_branches", "plan_id", "club_membership_plans"),
    ("club_membership_plans", "club_id", "clubs"),
    ("club_membership_sale_keys", "membership_subscription_id", "club_membership_subscriptions"),
    ("club_membership_subscriptions", "branch_id", "branches"),
    ("club_membership_subscriptions", "club_id", "clubs"),
    ("club_membership_subscriptions", "customer_id", "customers"),
    ("club_membership_subscriptions", "plan_id", "club_membership_plans"),
    ("club_memberships", "club_id", "clubs"),
    ("club_modules", "club_id", "clubs"),
    ("club_role_permissions", "club_role_id", "club_roles"),
    ("club_role_permissions", "permission_id", "permissions"),
    ("club_roles", "club_id", "clubs"),
    ("commercial_entitlements", "club_id", "clubs"),
    ("commercial_upgrade_requests", "club_id", "clubs"),
    ("customer_photo_update_requests", "club_id", "clubs"),
    ("customers", "club_id", "clubs"),
    ("employee_cash_liabilities", "branch_id", "branches"),
    ("employee_cash_liabilities", "cash_shift_id", "cash_shifts"),
    ("employee_cash_liabilities", "club_id", "clubs"),
    ("employee_cash_liability_ledger", "liability_id", "employee_cash_liabilities"),
    ("employee_cash_liability_settlement_keys", "liability_id", "employee_cash_liabilities"),
    ("enrollments", "club_id", "clubs"),
    ("enrollments", "group_id", "groups"),
    ("enrollments", "player_id", "players"),
    ("expense_categories", "club_id", "clubs"),
    ("expenses", "branch_id", "branches"),
    ("expenses", "club_id", "clubs"),
    ("field_blocks", "club_id", "clubs"),
    ("field_blocks", "field_id", "fields"),
    ("field_operating_hours", "club_id", "clubs"),
    ("fields", "branch_id", "branches"),
    ("fields", "club_id", "clubs"),
    ("gateway_webhook_rate_limit_state", "provider_key", "payment_gateway_providers"),
    ("government_collection_policies", "club_id", "clubs"),
    ("group_schedule_slots", "group_id", "groups"),
    ("groups", "branch_id", "branches"),
    ("groups", "club_id", "clubs"),
    ("guardian_links", "customer_id", "customers"),
    ("guardian_links", "player_id", "players"),
    ("invoice_items", "invoice_id", "invoices"),
    ("invoice_number_sequences", "branch_id", "branches"),
    ("invoice_verification_tokens", "club_id", "clubs"),
    ("invoice_verification_tokens", "invoice_id", "invoices"),
    ("invoices", "branch_id", "branches"),
    ("invoices", "club_id", "clubs"),
    ("invoices", "customer_id", "customers"),
    ("manual_payment_claims", "club_id", "clubs"),
    ("manual_payment_claims", "invoice_id", "invoices"),
    ("membership_branches", "branch_id", "branches"),
    ("membership_branches", "membership_id", "club_memberships"),
    ("messaging_safety_settings", "club_id", "clubs"),
    ("notification_category_settings", "club_id", "clubs"),
    ("notification_consent", "club_id", "clubs"),
    ("notification_consent", "customer_id", "customers"),
    ("notification_events", "club_id", "clubs"),
    ("notification_queue", "club_id", "clubs"),
    ("notification_suppressions", "club_id", "clubs"),
    ("notification_suppressions", "customer_id", "customers"),
    ("official_collection_receipts", "club_id", "clubs"),
    ("payment_allocations", "invoice_id", "invoices"),
    ("payment_allocations", "payment_id", "payments"),
    ("payment_gateway_configs", "club_id", "clubs"),
    ("payment_gateway_transactions", "club_id", "clubs"),
    ("payment_gateway_transactions", "invoice_id", "invoices"),
    ("payment_gateway_webhook_events", "provider_key", "payment_gateway_providers"),
    ("payment_method_configs", "club_id", "clubs"),
    ("payment_proofs", "club_id", "clubs"),
    ("payment_proofs", "invoice_id", "invoices"),
    ("payment_reconciliations", "club_id", "clubs"),
    ("payments", "branch_id", "branches"),
    ("payments", "club_id", "clubs"),
    ("payments", "customer_id", "customers"),
    ("permission_dependencies", "permission_key", "permissions"),
    ("permission_dependencies", "requires_key", "permissions"),
    ("platform_custom_role_permissions", "platform_custom_role_id", "platform_custom_roles"),
    ("platform_custom_role_permissions", "platform_permission_id", "platform_permissions"),
    ("platform_invoices", "club_id", "clubs"),
    ("platform_invoices", "platform_subscription_id", "platform_subscriptions"),
    ("platform_owner_pinned_clubs", "club_id", "clubs"),
    ("platform_owner_recent_clubs", "club_id", "clubs"),
    ("platform_payments", "platform_invoice_id", "platform_invoices"),
    ("platform_role_permissions", "platform_permission_id", "platform_permissions"),
    ("platform_role_permissions", "platform_role_id", "platform_roles"),
    ("platform_subscriptions", "club_id", "clubs"),
    ("platform_support_sessions", "club_id", "clubs"),
    ("players", "club_id", "clubs"),
    ("portal_invites", "club_id", "clubs"),
    ("portal_invites", "customer_id", "customers"),
    ("pricing_rules", "club_id", "clubs"),
    ("programs", "club_id", "clubs"),
    ("qr_credentials", "club_id", "clubs"),
    ("refunds", "payment_id", "payments"),
    ("role_permissions", "permission_id", "permissions"),
    ("role_permissions", "role_id", "roles"),
    ("seasons", "club_id", "clubs"),
    ("shop_categories", "club_id", "clubs"),
    ("shop_held_sale_items", "held_sale_id", "shop_held_sales"),
    ("shop_held_sale_items", "product_id", "shop_products"),
    ("shop_held_sales", "club_id", "clubs"),
    ("shop_inventory_balances", "club_id", "clubs"),
    ("shop_inventory_balances", "location_id", "shop_inventory_locations"),
    ("shop_inventory_balances", "product_id", "shop_products"),
    ("shop_inventory_locations", "club_id", "clubs"),
    ("shop_inventory_movements", "club_id", "clubs"),
    ("shop_inventory_movements", "location_id", "shop_inventory_locations"),
    ("shop_inventory_movements", "product_id", "shop_products"),
    ("shop_product_variants", "club_id", "clubs"),
    ("shop_product_variants", "product_id", "shop_products"),
    ("shop_products", "club_id", "clubs"),
    ("shop_sale_items", "product_id", "shop_products"),
    ("shop_sale_items", "sale_id", "shop_sales"),
    ("shop_sale_return_items", "return_id", "shop_sale_returns"),
    ("shop_sale_return_items", "sale_item_id", "shop_sale_items"),
    ("shop_sale_returns", "club_id", "clubs"),
    ("shop_sale_returns", "sale_id", "shop_sales"),
    ("shop_sales", "club_id", "clubs"),
    ("shop_sales", "location_id", "shop_inventory_locations"),
    ("shop_stock_count_items", "product_id", "shop_products"),
    ("shop_stock_count_items", "stock_count_id", "shop_stock_counts"),
    ("shop_stock_counts", "club_id", "clubs"),
    ("shop_stock_counts", "location_id", "shop_inventory_locations"),
    ("shop_suppliers", "club_id", "clubs"),
    ("subscription_freezes", "club_id", "clubs"),
    ("subscription_freezes", "subscription_id", "subscriptions"),
    ("subscriptions", "club_id", "clubs"),
    ("subscriptions", "enrollment_id", "enrollments"),
    ("training_sessions", "club_id", "clubs"),
    ("training_sessions", "group_id", "groups"),
    ("whatsapp_accounts", "club_id", "clubs"),
    ("whatsapp_connection_events", "club_id", "clubs"),
    ("whatsapp_delivery_traces", "club_id", "clubs"),
    ("whatsapp_incidents", "club_id", "clubs"),
]

# Nullable FK edges. These do NOT constrain insert order (column can be
# NULL at insert time) but DO need a deferred UPDATE pass after both
# sides exist, to avoid silently leaving them NULL forever on restore.
# Format: (table, fk_column, references_table).
SOFT_EDGES = [
    ("audit_logs", "branch_id", "branches"),
    ("audit_logs", "club_id", "clubs"),
    ("audit_logs", "support_session_id", "platform_support_sessions"),
    ("bookings", "booking_series_id", "booking_series"),
    ("bookings", "invoice_id", "invoices"),
    ("club_membership_subscriptions", "invoice_id", "invoices"),
    ("club_memberships", "custom_role_id", "club_roles"),
    ("club_memberships", "role_id", "roles"),
    ("customer_photo_update_requests", "customer_id", "customers"),
    ("customer_photo_update_requests", "player_id", "players"),
    ("expenses", "cash_shift_id", "cash_shifts"),
    ("expenses", "category_id", "expense_categories"),
    ("field_operating_hours", "branch_id", "branches"),
    ("field_operating_hours", "field_id", "fields"),
    ("government_collection_policies", "branch_id", "branches"),
    ("government_collection_policies", "field_id", "fields"),
    ("groups", "age_group_id", "age_groups"),
    ("groups", "field_id", "fields"),
    ("groups", "program_id", "programs"),
    ("groups", "season_id", "seasons"),
    ("enrollments", "guardian_id", "customers"),
    ("manual_payment_claims", "payment_method_config_id", "payment_method_configs"),
    ("manual_payment_claims", "resulting_payment_id", "payments"),
    ("notification_queue", "event_id", "notification_events"),
    ("notification_queue", "recipient_customer_id", "customers"),
    ("official_collection_receipts", "booking_id", "bookings"),
    ("official_collection_receipts", "branch_id", "branches"),
    ("official_collection_receipts", "customer_id", "customers"),
    ("official_collection_receipts", "field_id", "fields"),
    ("official_collection_receipts", "invoice_id", "invoices"),
    ("official_collection_receipts", "payment_id", "payments"),
    ("payment_gateway_transactions", "connection_id", "club_gateway_connections"),
    ("payment_gateway_transactions", "payment_id", "payments"),
    ("payment_gateway_webhook_events", "connection_id", "club_gateway_connections"),
    ("payment_gateway_webhook_events", "transaction_id", "payment_gateway_transactions"),
    ("payment_proofs", "booking_id", "bookings"),
    ("payment_proofs", "customer_id", "customers"),
    ("payment_proofs", "payment_method_config_id", "payment_method_configs"),
    ("payment_proofs", "resulting_payment_id", "payments"),
    ("payment_reconciliations", "branch_id", "branches"),
    ("payments", "cash_shift_id", "cash_shifts"),
    ("platform_staff_memberships", "platform_custom_role_id", "platform_custom_roles"),
    ("platform_staff_memberships", "platform_role_id", "platform_roles"),
    ("platform_subscriptions", "plan_id", "platform_plans"),
    ("portal_invites", "triggering_booking_id", "bookings"),
    ("pricing_rules", "field_id", "fields"),
    ("qr_scan_events", "club_id", "clubs"),
    ("qr_scan_events", "credential_id", "qr_credentials"),
    ("refunds", "cash_shift_id", "cash_shifts"),
    ("seasons", "program_id", "programs"),
    ("shop_held_sale_items", "variant_id", "shop_product_variants"),
    ("shop_held_sales", "customer_id", "customers"),
    ("shop_inventory_balances", "variant_id", "shop_product_variants"),
    ("shop_inventory_locations", "branch_id", "branches"),
    ("shop_inventory_movements", "variant_id", "shop_product_variants"),
    ("shop_products", "category_id", "shop_categories"),
    ("shop_sale_items", "invoice_item_id", "invoice_items"),
    ("shop_sale_items", "variant_id", "shop_product_variants"),
    ("shop_sale_returns", "refund_payment_id", "refunds"),
    ("shop_sales", "customer_id", "customers"),
    ("shop_sales", "invoice_id", "invoices"),
    ("shop_stock_count_items", "movement_id", "shop_inventory_movements"),
    ("shop_stock_count_items", "variant_id", "shop_product_variants"),
    ("subscriptions", "invoice_id", "invoices"),
    ("training_sessions", "field_id", "fields"),
    ("whatsapp_delivery_traces", "notification_queue_id", "notification_queue"),
    ("whatsapp_incidents", "root_cause_code", "whatsapp_root_cause_codes"),
]

# Self-referencing FK columns (child table references its own PK).
# Always nullable in this schema; never constrains between-table order,
# but must be inserted NULL and backfilled in the same deferred pass as
# SOFT_EDGES to correctly restore the relationship.
SELF_REF_COLUMNS = [
    ("customers", "merged_into_customer_id"),
    ("platform_subscriptions", "previous_subscription_id"),
    ("official_collection_receipts", "corrected_from_receipt_id"),
]


def topo_sort(tables, hard_edges):
    """Kahn's algorithm. Returns (order, cycle) -- cycle is a non-empty
    list of tables still unresolved if one exists (should be empty for
    a valid DAG); order is a best-effort partial order in that case."""
    deps = {t: set() for t in tables}  # table -> set of tables it depends on (parents)
    for child, _col, parent in hard_edges:
        if child == parent:
            continue  # self-refs never constrain between-table order
        deps[child].add(parent)

    in_degree = {t: len(deps[t]) for t in tables}
    # Stable, deterministic order: process zero-in-degree nodes in
    # original ALL_TABLES order (not arbitrary set order) so re-runs
    # produce byte-identical output.
    ready = [t for t in tables if in_degree[t] == 0]
    order = []
    # dependents[parent] = tables that depend on parent
    dependents = {t: [] for t in tables}
    for child, parents in deps.items():
        for p in parents:
            dependents[p].append(child)

    while ready:
        ready.sort(key=lambda t: tables.index(t))
        node = ready.pop(0)
        order.append(node)
        for dependent in dependents[node]:
            in_degree[dependent] -= 1
            if in_degree[dependent] == 0:
                ready.append(dependent)

    remaining = [t for t in tables if t not in order]
    return order, remaining


def forward_reference_defer_cols(order):
    """Returns {table: [[pk_col, fk_col], ...]} for every soft edge and
    self-ref column that is a genuine forward reference given `order`
    (child restored before its parent) -- i.e. the only ones where a
    real non-NULL value in that column can break a straight INSERT and
    therefore needs NULL-at-insert + deferred UPDATE. Soft edges whose
    parent is already earlier in `order` never need this treatment.
    Assumes every table's primary key column is named 'id'. Verified
    true for all 17 tables that actually appear in this function's
    output, via a live query against every one of them:
        select c.relname, a.attname from pg_constraint con
        join pg_class c on c.oid = con.conrelid
        join pg_attribute a on a.attrelid = c.oid and a.attnum = any(con.conkey)
        where con.contype = 'p' and c.relnamespace = 'public'::regnamespace;
    -- re-run this check (or extend it to whichever tables newly appear
    -- in the output) if the schema changes and a table with a
    -- composite or non-'id' primary key ever needs a defer_cols entry;
    -- this function does not verify it at runtime."""
    pos = {t: i for i, t in enumerate(order)}
    result = {}
    for child, col, parent in SOFT_EDGES:
        if pos[child] < pos[parent]:
            result.setdefault(child, []).append(["id", col])
    for table, col in SELF_REF_COLUMNS:
        result.setdefault(table, []).append(["id", col])
    return result


def main():
    args = sys.argv[1:]
    verify_only = "--verify" in args
    as_json = "--json" in args
    defer_cols_only = "--defer-cols" in args

    # Sanity: every table referenced in HARD_EDGES/SOFT_EDGES must be a
    # known table (catches typos / stale edge list vs. ALL_TABLES).
    all_set = set(ALL_TABLES)
    unknown = set()
    for child, _col, parent in HARD_EDGES + SOFT_EDGES:
        if child not in all_set:
            unknown.add(child)
        if parent not in all_set:
            unknown.add(parent)
    if unknown:
        print(f"ERROR: edge list references unknown table(s): {sorted(unknown)}", file=sys.stderr)
        sys.exit(2)

    order, cycle = topo_sort(ALL_TABLES, HARD_EDGES)

    if cycle:
        print("ERROR: cycle detected among NOT NULL (hard) foreign keys -- "
              "no valid insert order exists without a schema change "
              "(e.g. making one of these FKs nullable or deferrable).",
              file=sys.stderr)
        print(f"Unresolved tables (mutually or transitively cyclic): {sorted(cycle)}", file=sys.stderr)
        sys.exit(1)

    if verify_only:
        print(f"OK: valid topological order exists for all {len(ALL_TABLES)} tables, "
              f"{len(HARD_EDGES)} hard edges, 0 cycles.")
        sys.exit(0)

    if defer_cols_only:
        defer_cols = forward_reference_defer_cols(order)
        print(json.dumps(defer_cols, indent=2))
        sys.exit(0)

    defer_cols = forward_reference_defer_cols(order)

    if as_json:
        print(json.dumps({
            "restore_order": order,
            "hard_edge_count": len(HARD_EDGES),
            "soft_edge_count": len(SOFT_EDGES),
            "defer_cols": defer_cols,
            "self_ref_columns": [{"table": t, "column": c} for t, c in SELF_REF_COLUMNS],
        }, indent=2))
    else:
        print("-- Correct FK-dependency-safe table restore order")
        print(f"-- {len(order)} tables, {len(HARD_EDGES)} hard (NOT NULL FK) edges enforced, 0 cycles")
        print("-- Tables needing a deferred UPDATE pass (forward-referencing nullable/self-ref FKs):")
        deferred = sorted(defer_cols.keys())
        print(f"--   {', '.join(deferred)}")
        print()
        for i, t in enumerate(order, 1):
            print(f"{i:3d}. {t}")


if __name__ == "__main__":
    main()
