-- Platform Owner WhatsApp QR never appearing -- REAL ROOT CAUSE FIX
-- (2026-09-18, owner-reported, confirmed live).
--
-- Prior fixes in this same investigation (whatsapp-wake-connector Edge
-- Function) correctly diagnosed and fixed "nothing wakes the sleeping
-- container" for both the club-scoped and platform-scoped WhatsApp
-- domains. Waking the platform account's container surfaced a SECOND,
-- deeper bug, confirmed live via platform_whatsapp_connection_events:
-- every status write the freshly-woken connector attempted was
-- rejected as stale (status_write_rejected_stale), because
-- PlatformConnectionManager.ts hardcodes `generation: 0` on every
-- process start (see its own now-outdated comment: "there is no
-- accumulated prior-restart generation count in the database to
-- collide with yet, so 0 is a genuine, correct starting point"). That
-- was true when the Platform WhatsApp domain was brand new, but the
-- connector had since run for real (2026-09-13, generation 0,
-- state_seq climbing to 8346 before giving up after 941 reconnect
-- attempts) -- so every later restart's writes (generation 0, state_seq
-- starting at 1) were permanently less than the database's remembered
-- high-water mark (generation 0, state_seq 8346), and
-- whatsapp_connector_report_platform_status()'s own fencing check
-- (correctly) rejected every single one, forever, with zero visible
-- error to the owner -- the QR was being generated by Baileys but could
-- never actually be written to a column the frontend reads.
--
-- This is the exact same class of bug the tenant/club WhatsApp domain
-- already solved via whatsapp_connector_claim_generation() (see that
-- function, migration history) -- an atomic claim-and-increment RPC
-- called once per connector process start, so a fresh process always
-- claims a generation strictly greater than anything already recorded,
-- with state_seq reset to 0 under that new generation. This migration
-- adds the platform-domain equivalent, mirroring that function's exact
-- shape for the platform_whatsapp_account singleton row.

create or replace function public.whatsapp_connector_claim_platform_generation()
returns integer
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $$
declare
  v_new_generation integer;
begin
  select last_generation + 1
    into v_new_generation
  from public.platform_whatsapp_account
  where singleton_guard = 1
  for update;

  update public.platform_whatsapp_account
  set last_generation = v_new_generation,
      last_state_seq = 0,
      updated_at = now()
  where singleton_guard = 1;

  insert into public.platform_whatsapp_connection_events (event, actor_id, detail)
  values ('generation_claimed', null, jsonb_build_object('new_generation', v_new_generation));

  return v_new_generation;
end;
$$;

-- Same grant shape as every other whatsapp_connector_* RPC in this
-- domain (20260909200000_platform_whatsapp_domain.sql) -- service_role
-- only, explicitly revoked from public/anon/authenticated so a
-- DROP+CREATE-free CREATE OR REPLACE here cannot silently leave a
-- default PUBLIC grant behind (the exact lesson from this project's own
-- prior grant-leak incidents).
revoke all on function public.whatsapp_connector_claim_platform_generation() from public;
revoke all on function public.whatsapp_connector_claim_platform_generation() from anon;
revoke all on function public.whatsapp_connector_claim_platform_generation() from authenticated;
grant execute on function public.whatsapp_connector_claim_platform_generation() to service_role;
